import "server-only";

import type { PrismaClient } from "@prisma/client";

import { clientEnv } from "@/env";
import { site } from "@/lib/site";
import {
  emailButton,
  emailDivider,
  emailEyebrow,
  emailShell,
  emailStyles,
  escapeHtml,
  sendEmail,
  type SendResult,
} from "@/server/lib/email";
import { unsubscribeUrl } from "@/server/lib/unsubscribe";

/* ---------------------------------------------------------------------------
   The Monday email
   ---------------------------------------------------------------------------
   The product's answer to "what changed while I wasn't looking". It is a
   summary, not a dashboard: three themes, three quotes, one number. Anything
   longer gets skimmed and then filtered.

   Nothing here is generated by the model. Every figure is arithmetic over rows
   that already exist, so the email costs nothing to produce and cannot
   hallucinate a trend.
--------------------------------------------------------------------------- */

const { INK, STEEL, MINT, MINT_INK, MINT_DEEP, MINT_WASH, FONT } = emailStyles;

/** Mint hairline, used for the theme chips and the quote rules. */
const MINT_LINE = "#b4ead8";

export type DigestProject = {
  name: string;
  total: number;
  previous: number;
  negativeShare: number;
  themes: Array<{
    id: string;
    title: string;
    itemCount: number;
    negativeShare: number;
    isNew: boolean;
  }>;
  quotes: Array<{ body: string; sentiment: string | null }>;
};

export type Digest = {
  orgName: string;
  since: Date;
  projects: DigestProject[];
  total: number;
};

/**
 * Gathers a week of activity for one organization.
 *
 * Returns null when there is nothing to say. An empty weekly email is how a
 * useful product teaches people to ignore it.
 */
export async function buildDigest(
  db: PrismaClient,
  orgId: string,
  now = new Date(),
): Promise<Digest | null> {
  const since = new Date(now);
  since.setDate(since.getDate() - 7);
  const previousSince = new Date(since);
  previousSince.setDate(previousSince.getDate() - 7);

  const org = await db.organization.findUnique({
    where: { id: orgId },
    select: { name: true, projects: { select: { id: true, name: true } } },
  });
  if (!org) return null;

  const projects: DigestProject[] = [];

  for (const project of org.projects) {
    const [items, previous, themes] = await Promise.all([
      db.feedback.findMany({
        where: { projectId: project.id, createdAt: { gte: since } },
        select: {
          body: true,
          sentiment: true,
          summary: true,
          createdAt: true,
        },
        orderBy: { createdAt: "desc" },
      }),
      db.feedback.count({
        where: {
          projectId: project.id,
          createdAt: { gte: previousSince, lt: since },
        },
      }),
      db.theme.findMany({
        where: { projectId: project.id, status: "ACTIVE" },
        orderBy: { priorityScore: "desc" },
        take: 3,
        select: {
          id: true,
          title: true,
          itemCount: true,
          negativeShare: true,
          firstSeenAt: true,
        },
      }),
    ]);

    if (items.length === 0 && themes.length === 0) continue;

    const negative = items.filter((i) => i.sentiment === "NEGATIVE").length;

    projects.push({
      name: project.name,
      total: items.length,
      previous,
      negativeShare: items.length > 0 ? negative / items.length : 0,
      themes: themes.map((t) => ({
        id: t.id,
        title: t.title,
        itemCount: t.itemCount,
        negativeShare: t.negativeShare,
        isNew: t.firstSeenAt >= since,
      })),
      // Quotes are the receipts. Negative first, because those are the ones
      // worth reading on a Monday.
      quotes: [...items]
        .sort((a, b) =>
          (a.sentiment === "NEGATIVE" ? 0 : 1) -
          (b.sentiment === "NEGATIVE" ? 0 : 1),
        )
        .slice(0, 3)
        .map((i) => ({ body: i.summary ?? i.body, sentiment: i.sentiment })),
    });
  }

  const total = projects.reduce((sum, p) => sum + p.total, 0);
  if (projects.length === 0 || total === 0) return null;

  return { orgName: org.name, since, projects, total };
}

function changeLine(total: number, previous: number): string {
  if (previous === 0) {
    return total > 0 ? "first week of feedback" : "no change";
  }
  const delta = Math.round(((total - previous) / previous) * 100);
  if (delta === 0) return "level with last week";
  return `${delta > 0 ? "up" : "down"} ${Math.abs(delta)}% on last week`;
}

export function renderDigest(
  digest: Digest,
  optOutUrl: string | null = null,
): { html: string; text: string } {
  const appUrl = clientEnv.NEXT_PUBLIC_APP_URL;
  const week = digest.since.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
  });

  const sections = digest.projects
    .map((project) => {
      const themes = project.themes
        .map((theme, index) => {
          const share = Math.round(theme.negativeShare * 100);
          return `
        <tr>
          <td style="padding:0 0 9px">
            <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
            <tr>
              <td width="24" valign="top" style="padding:1px 11px 0 0;line-height:0;font-size:0">
                <div class="vb-wash vb-chip" style="width:22px;height:22px;background:${MINT_WASH};border:1px solid ${MINT_LINE};border-radius:6px;font-family:${FONT};font-size:11.5px;font-weight:700;color:${MINT_DEEP};text-align:center;line-height:21px">${index + 1}</div>
              </td>
              <td valign="top" style="font-family:${FONT}">
                <a href="${appUrl}/app/themes/${theme.id}" class="vb-ink" style="font-family:${FONT};font-size:14.5px;font-weight:600;line-height:1.4;letter-spacing:-0.012em;color:${INK};text-decoration:none">${escapeHtml(theme.title)}</a>${
                  theme.isNew
                    ? `<span style="display:inline-block;margin-left:8px;background:${MINT};color:${MINT_INK};font-family:${FONT};font-size:9.5px;font-weight:700;letter-spacing:0.06em;padding:2px 6px;border-radius:99px;vertical-align:2px">NEW</span>`
                    : ""
                }
                <div class="vb-steel" style="font-family:${FONT};font-size:12.5px;line-height:1.5;color:${STEEL};padding-top:3px">
                  ${theme.itemCount} ${theme.itemCount === 1 ? "mention" : "mentions"}${share > 0 ? ` &middot; ${share}% negative` : ""}
                </div>
              </td>
            </tr>
            </table>
          </td>
        </tr>`;
        })
        .join("");

      const quotes = project.quotes
        .map(
          (quote) => `
        <tr>
          <td class="vb-ink" style="padding:0 0 12px;font-family:${FONT}">
            <div class="vb-ink vb-quote" style="border-left:3px solid ${MINT_LINE};padding:1px 0 1px 14px;font-family:${FONT};font-size:14px;font-weight:400;line-height:1.62;color:${INK}">
              ${escapeHtml(quote.body.slice(0, 220))}${quote.body.length > 220 ? "&hellip;" : ""}
            </div>
          </td>
        </tr>`,
        )
        .join("");

      return `
      ${emailDivider(26, 24)}
      <div class="vb-ink" style="font-family:${FONT};font-size:17px;font-weight:700;letter-spacing:-0.024em;line-height:1.3;color:${INK}">${escapeHtml(project.name)}</div>
      <div class="vb-steel" style="font-family:${FONT};font-size:13px;line-height:1.5;color:${STEEL};padding:4px 0 0">
        ${project.total} new ${project.total === 1 ? "piece" : "pieces"}, ${changeLine(project.total, project.previous)}
      </div>

      ${
        project.themes.length > 0
          ? `<div style="padding-top:20px">${emailEyebrow("What to work on")}</div>
             <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">${themes}</table>`
          : `<div class="vb-steel" style="font-family:${FONT};font-size:13px;line-height:1.6;color:${STEEL};padding-top:14px">Not enough yet for a pattern. Themes appear once the same problem shows up a few times.</div>`
      }

      ${
        project.quotes.length > 0
          ? `<div style="padding:22px 0 0">${emailEyebrow("Worth reading")}</div>
             <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">${quotes}</table>`
          : ""
      }`;
    })
    .join("");

  const body = `
    <div class="vb-h1 vb-ink" style="font-family:${FONT};font-size:22px;font-weight:700;letter-spacing:-0.03em;line-height:1.25;color:${INK}">
      ${digest.total} new ${digest.total === 1 ? "piece" : "pieces"} of feedback this week.
    </div>
    <div class="vb-steel" style="font-family:${FONT};font-size:15px;line-height:1.6;color:${STEEL};padding:9px 0 0">
      Here's what your users have been saying since ${week}.
    </div>
    ${sections}
    ${emailDivider(28, 26)}
    ${emailButton(`${appUrl}/app`, "Open the dashboard")}`;

  const text = [
    `${digest.orgName}: ${digest.total} new ${digest.total === 1 ? "piece" : "pieces"} of feedback this week.`,
    "",
    ...digest.projects.flatMap((project) => [
      `${project.name}, ${project.total} new (${changeLine(project.total, project.previous)})`,
      ...project.themes.map(
        (theme, i) =>
          `  ${i + 1}. ${theme.title}, ${theme.itemCount} ${theme.itemCount === 1 ? "mention" : "mentions"}${theme.isNew ? " (new)" : ""}`,
      ),
      "",
    ]),
    `Open the dashboard: ${appUrl}/app`,
    "",
    "—",
    // The text part gets the same footer as the HTML. A recipient reading
    // plain text was previously given a recurring email with no sender
    // identity and no way out.
    `You're getting this because weekly digests are on for ${digest.orgName}.`,
    optOutUrl
      ? `Unsubscribe: ${optOutUrl}`
      : `Manage email preferences: ${appUrl}/app/settings/general`,
    site.legalEntity,
  ].join("\n");

  return {
    html: emailShell({
      title: `Your week on ${site.name}`,
      preview: `${digest.total} new pieces of feedback, and the themes worth acting on.`,
      body,
      footer:
        `You're getting this because weekly digests are on for ${escapeHtml(digest.orgName)}. ` +
        (optOutUrl
          ? `<a href="${optOutUrl}" class="vb-steel" style="color:${STEEL};text-decoration:underline">Unsubscribe</a>, or `
          : "") +
        `<a href="${appUrl}/app/settings/general" class="vb-steel" style="color:${STEEL};text-decoration:underline">manage preferences</a>.`,
    }),
    text,
  };
}

/**
 * @param membershipId when present, the message carries a one-click
 * unsubscribe for that person. Omitted for the self-service preview, which the
 * caller asked for and should not be able to unsubscribe from.
 */
export function sendDigest(
  to: string,
  digest: Digest,
  membershipId?: string,
): Promise<SendResult> {
  const optOut = membershipId
    ? unsubscribeUrl(clientEnv.NEXT_PUBLIC_APP_URL, membershipId)
    : null;
  const { html, text } = renderDigest(digest, optOut);

  return sendEmail({
    to,
    subject: `${digest.orgName}: ${digest.total} new ${digest.total === 1 ? "piece" : "pieces"} of feedback, and what to do about it`,
    html,
    text,
    // RFC 8058: lets Gmail and Yahoo render their own unsubscribe control and
    // fire it as a POST, with no page load and no sign-in.
    ...(optOut
      ? {
          headers: {
            "List-Unsubscribe": `<${optOut}>`,
            "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
          },
        }
      : {}),
  });
}
